runtime: php74

entrypoint: serve public/index.php

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 0

default_expiration: "1d"

handlers:
- url: /.*
  script: auto
  secure: always

includes:
  - env_variables.yaml
